name: thermal
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pandas
  - fiona
  - matplotlib
  - tqdm
  - spyder
  - jupyter
  - cartopy
  - xarray
  - netCDF4
  - cmocean
  - geopandas
  - rioxarray
  - html5lib
  - numpy
  - pyogrio
  - dask
  - dask-geopandas
  - seaborn
  - bs4
  - eppy-core
  - xmltodict
  - openpyxl
  - unidecode
  - pysolar
  - geopy
  - shapely
  - cdsapi
  - fastparquet
  - pytables
  - pyarrow
 # - requests_cache
  #- pip:
  #	- openmeteo-requests
  #	- retry-requests	
 #     - eppy
